import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, '..');
const checkOnly = process.argv.includes('--check');

const sourceFiles = [
  'primitive.json',
  'theme.json',
  'semantic-color.json',
  'density.json',
  'layout.json',
  'typography.json',
  'motion.json',
];

const collections = [];
for (const file of sourceFiles) {
  collections.push(JSON.parse(await readFile(resolve(pkg, 'source', file), 'utf8')));
}

const expectedCounts = {
  'FG / Primitive Color': 93,
  'FG / Theme': 25,
  'FG / Semantic Color': 73,
  'FG / Density': 17,
  'FG / Layout': 63,
  'FG / Typography': 29,
  'FG / Motion': 7,
};

const collectionMap = new Map(collections.map((c) => [c.collection, c]));
const total = collections.reduce((sum, c) => sum + Object.keys(c.tokens).length, 0);
if (total !== 307) throw new Error(`FORGE expects 307 tokens; found ${total}`);
for (const [name, count] of Object.entries(expectedCounts)) {
  const actual = Object.keys(collectionMap.get(name)?.tokens ?? {}).length;
  if (actual !== count) throw new Error(`${name}: expected ${count}, found ${actual}`);
}

const prefixByCollection = {
  'FG / Primitive Color': 'primitive',
  'FG / Theme': 'theme',
  'FG / Semantic Color': 'semantic',
  'FG / Density': 'density',
  'FG / Layout': 'layout',
  'FG / Typography': 'type',
  'FG / Motion': 'motion',
};

const modeKeyByCollection = {
  'FG / Primitive Color': 'value',
  'FG / Theme': 'theme',
  'FG / Semantic Color': 'colorMode',
  'FG / Density': 'density',
  'FG / Layout': 'value',
  'FG / Typography': 'value',
  'FG / Motion': 'motion',
};

const defaultModes = {
  theme: 'Neutral',
  colorMode: 'Light',
  density: 'Comfortable',
  motion: 'Standard',
};

function kebab(value) {
  return value
    .replaceAll('/', '-')
    .replaceAll(' ', '-')
    .replace(/[^a-zA-Z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .toLowerCase();
}

function snake(value) {
  return kebab(value).replaceAll('-', '_');
}

function pascal(value) {
  return kebab(value)
    .split('-')
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

function cssName(collection, token) {
  return `--fg-${prefixByCollection[collection]}-${kebab(token)}`;
}

function androidName(collection, token) {
  return `fg_${prefixByCollection[collection]}_${snake(token)}`;
}

function iosName(collection, token) {
  return `FGTokens.${prefixByCollection[collection]}${pascal(token)}`;
}

const aliasPattern = /^\{(.+?)::(.+)\}$/;
function parseAlias(value) {
  if (typeof value !== 'string') return null;
  const match = value.match(aliasPattern);
  return match ? { collection: match[1], token: match[2] } : null;
}

// Verify all aliases are valid.
for (const collection of collections) {
  for (const [tokenName, token] of Object.entries(collection.tokens)) {
    for (const mode of collection.modes) {
      const alias = parseAlias(token[mode]);
      if (alias && !collectionMap.get(alias.collection)?.tokens?.[alias.token]) {
        throw new Error(`Broken alias ${collection.collection}::${tokenName} -> ${token[mode]}`);
      }
    }
  }
}

function cssValue(collectionName, tokenName, token, mode) {
  const raw = token[mode];
  const alias = parseAlias(raw);
  if (alias) return `var(${cssName(alias.collection, alias.token)})`;
  if (token.type === 'COLOR') return raw;
  if (token.type === 'STRING') {
    if (collectionName === 'FG / Typography' && tokenName.startsWith('family/')) return JSON.stringify(raw);
    return raw;
  }
  if (token.type === 'FLOAT') {
    if (collectionName === 'FG / Density') return `${raw}px`;
    if (collectionName === 'FG / Layout') return tokenName.startsWith('opacity/') ? `${raw}` : `${raw}px`;
    if (collectionName === 'FG / Typography') {
      if (tokenName.startsWith('weight/')) return `${raw}`;
      return `${raw}px`;
    }
    if (collectionName === 'FG / Motion') return tokenName.startsWith('duration/') ? `${raw}ms` : `${raw}`;
  }
  return `${raw}`;
}

function declarationBlock(collectionName, mode) {
  const c = collectionMap.get(collectionName);
  return Object.entries(c.tokens)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, token]) => `  ${cssName(collectionName, name)}: ${cssValue(collectionName, name, token, mode)};`)
    .join('\n');
}

function modeSlug(mode) {
  return kebab(mode);
}

const css = [
  '/* AUTO-GENERATED by @forge/tokens. Do not edit directly. */',
  '/* Source: FORGE v1 Figma variables — 307 tokens / 7 collections. */',
  '',
  ':root {',
  declarationBlock('FG / Primitive Color', 'Value'),
  declarationBlock('FG / Layout', 'Value'),
  declarationBlock('FG / Typography', 'Value'),
  '}',
  '',
];

function addModeAxis(collectionName, attribute, defaultMode) {
  const c = collectionMap.get(collectionName);
  for (const mode of c.modes) {
    const selector = mode === defaultMode
      ? `:root, [${attribute}="${modeSlug(mode)}"]`
      : `[${attribute}="${modeSlug(mode)}"]`;
    css.push(`${selector} {`);
    css.push(declarationBlock(collectionName, mode));
    css.push('}', '');
  }
}

addModeAxis('FG / Theme', 'data-forge-theme', 'Neutral');
addModeAxis('FG / Semantic Color', 'data-forge-color-mode', 'Light');
addModeAxis('FG / Density', 'data-forge-density', 'Comfortable');
addModeAxis('FG / Motion', 'data-forge-motion', 'Standard');

const canonicalJson = {
  schemaVersion: 1,
  source: {
    system: 'FORGE v1',
    figmaFileKey: 'fsCvPcjtvgfHQsw4DnLw7H',
    variableCount: 307,
  },
  defaultModes,
  collections,
};

const syntax = {};
for (const c of collections) {
  syntax[c.collection] = {};
  for (const token of Object.keys(c.tokens).sort()) {
    syntax[c.collection][token] = {
      web: `var(${cssName(c.collection, token)})`,
      android: androidName(c.collection, token),
      iOS: iosName(c.collection, token),
    };
  }
}

const generatedTs = `/* AUTO-GENERATED by @forge/tokens. Do not edit directly. */\n` +
`export const forgeTokenSource = ${JSON.stringify(canonicalJson, null, 2)} as const;\n\n` +
`export const forgeCodeSyntax = ${JSON.stringify(syntax, null, 2)} as const;\n\n` +
`export const forgeThemes = ['neutral', 'clinical', 'cyber', 'organic', 'premium'] as const;\n` +
`export const forgeColorModes = ['light', 'dark', 'hc-light', 'hc-dark'] as const;\n` +
`export const forgeDensities = ['compact', 'comfortable', 'touch'] as const;\n` +
`export const forgeMotions = ['standard', 'reduced'] as const;\n\n` +
`export type ForgeTheme = typeof forgeThemes[number];\n` +
`export type ForgeColorMode = typeof forgeColorModes[number];\n` +
`export type ForgeDensity = typeof forgeDensities[number];\n` +
`export type ForgeMotion = typeof forgeMotions[number];\n\n` +
`export const forgeRootAttributes = {\n` +
`  theme: 'data-forge-theme',\n` +
`  colorMode: 'data-forge-color-mode',\n` +
`  density: 'data-forge-density',\n` +
`  motion: 'data-forge-motion',\n` +
`} as const;\n`;

const outputs = new Map([
  [resolve(pkg, 'generated/css/forge.css'), css.join('\n') + '\n'],
  [resolve(pkg, 'generated/json/forge.tokens.json'), JSON.stringify(canonicalJson, null, 2) + '\n'],
  [resolve(pkg, 'generated/json/code-syntax.json'), JSON.stringify(syntax, null, 2) + '\n'],
  [resolve(pkg, 'src/generated.ts'), generatedTs],
]);

let stale = false;
for (const [path, content] of outputs) {
  if (checkOnly) {
    let existing = '';
    try { existing = await readFile(path, 'utf8'); } catch {}
    if (existing !== content) {
      console.error(`STALE: ${path.replace(pkg + '/', '')}`);
      stale = true;
    }
  } else {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content, 'utf8');
  }
}

if (checkOnly && stale) {
  console.error('Run `pnpm --filter @forge/tokens generate` and commit generated artifacts.');
  process.exit(1);
}

console.log(`FORGE tokens ${checkOnly ? 'verified' : 'generated'}: ${total} tokens across ${collections.length} collections.`);
